# ============================================================
#  Training Ground 通用配置
# ============================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: training-config
  namespace: __NAMESPACE__
data:
  PROVIDER: "deepseek"
  # PROVIDER: "openai"
  # CUSTOM_API_BASE: "http://0.0.0.0"
  # CUSTOM_MODEL: "deepseek-chat"
