import type { CaseDefinition } from "@tashuo/core";
import { STANDARD_STAGES } from "../shared.js";
const report = (a: string, b: string, c: string) => `${a}\n\n${b}\n\n${c}`;
export const BLUE_RIVER: CaseDefinition = {
 id: "blue-river", version: "1.0.0", title: "河水变蓝以后", synopsis: "暴雨后的蓝色河水与死鱼视频，把印染厂、管网工程和旧照片卷进同一个简单故事。", durationMinutes: 10_080, realSecondsPerGameMinute: 6, stages: STANDARD_STAGES,
 facts: [
  { id: "blue_video_real", statement: "最早蓝色河水视频时间地点真实。", truth: "true", importance: "critical", explanation: "多名居民的时间地点可互证。" }, { id: "tracer_primary", statement: "蓝色河水主要来自管网示踪剂。", truth: "true", importance: "critical", explanation: "作业公告与扩散路径支持。" }, { id: "tracer_overdose", statement: "示踪作业实际过量并经错接雨水管入河。", truth: "true", importance: "critical", explanation: "更正公告确认操作偏差。" }, { id: "fish_due_tracer", statement: "死鱼主要由示踪剂毒性造成。", truth: "false", importance: "critical", explanation: "鱼群异常早于蓝水。" }, { id: "sewer_overflow", statement: "暴雨雨污混流与低溶解氧是鱼群异常主因。", truth: "true", importance: "critical", explanation: "监测和时间线闭合。" }, { id: "factory_compliant", statement: "印染厂所有排放合规。", truth: "false", importance: "critical", explanation: "存在轻微超标。" }, { id: "factory_caused_blue", statement: "印染厂造成蓝色河水。", truth: "false", importance: "critical", explanation: "扩散路径来自管网。" }, { id: "old_fish_photo", statement: "热门死鱼照片拍于当日。", truth: "false", importance: "supporting", explanation: "照片来自两年前。" }, { id: "official_result_true", statement: "环境部门上午采样结果真实。", truth: "true", importance: "supporting", explanation: "问题是采样范围而非伪造。" }
 ],
 sources: [
  { id: "city_tv", name: "澜江电视台", kind: "tv", publicDescription: "本地突发新闻。", agenda: "时效", knownFactIds: ["blue_video_real"] }, { id: "river_radio_tv", name: "澜江民生台", kind: "tv", publicDescription: "河道安全新闻。", agenda: "居民风险", knownFactIds: ["sewer_overflow"] }, { id: "evening_news", name: "澜江晚报", kind: "newspaper", publicDescription: "城市治理报道。", agenda: "追查责任", knownFactIds: ["tracer_primary"] }, { id: "metropolitan_daily", name: "城市都市报", kind: "newspaper", publicDescription: "公共工程档案报道。", agenda: "核对合同", knownFactIds: ["tracer_overdose"] }, { id: "environment_office", name: "澜江市环境信息", kind: "official", publicDescription: "环境部门账号。", agenda: "发布确认信息", knownFactIds: ["official_result_true", "sewer_overflow"] }, { id: "beian_factory", name: "北岸印染", kind: "official", publicDescription: "企业账号。", agenda: "摆脱责任", knownFactIds: ["factory_compliant"] }, { id: "pipe_contractor", name: "清流管网工程", kind: "official", publicDescription: "承包商账号。", agenda: "淡化失误", knownFactIds: ["tracer_primary"] }, { id: "angler_he", name: "清平河老何", kind: "resident", publicDescription: "本地钓友。", agenda: "记录河况", knownFactIds: ["blue_video_real", "sewer_overflow"] }, { id: "green_watch", name: "绿色观察站", kind: "self_media", publicDescription: "环境热点账号。", agenda: "扩大影响", knownFactIds: ["old_fish_photo"] }
 ],
 contents: [
  { id: "river_first_clip", sourceId: "angler_he", kind: "short_video", publishedAtMinute: 0, title: "清平河怎么突然变蓝了", body: "东平码头附近河面呈亮蓝色，岸边有小鱼翻肚，桥上时钟显示06:18。", claims: [{ factId: "blue_video_real", relation: "supports" }, { factId: "fish_due_tracer", relation: "speculates" }], misleadingTechniques: [], commentsEnabled: true, trafficWeight: 10 },
  { id: "factory_accusation", sourceId: "green_watch", kind: "post", publishedAtMinute: 180, title: "上游九百米就是北岸印染厂", body: "贴文把旧处罚、河流地图和蓝水视频拼在一起，没有展示当日排水路径。", claims: [{ factId: "factory_caused_blue", relation: "supports" }], misleadingTechniques: ["causal_reversal"], commentsEnabled: true, trafficWeight: 10 },
  { id: "tv_morning_river", sourceId: "city_tv", kind: "tv_news", publishedAtMinute: 360, title: "环境部门已赴清平河采样", body: report("早间新闻确认视频地点，环境部门已到场采样并设置安全提示。", "现场工作人员提醒居民暂勿接触异常水体，鱼群情况和显色来源均在核查。", "节目没有把上游工厂与蓝色水体直接关联，称仍需等待排水路径和监测结果。"), claims: [{ factId: "blue_video_real", relation: "supports" }], misleadingTechniques: [], commentsEnabled: false, trafficWeight: 8 },
  { id: "factory_denial", sourceId: "beian_factory", kind: "official_notice", publishedAtMinute: 720, title: "我厂不存在蓝色染料夜间排放", body: "企业称各项生产正常，但没有展示当日排水路径。", claims: [{ factId: "factory_caused_blue", relation: "denies" }, { factId: "factory_compliant", relation: "supports" }], misleadingTechniques: ["selective_context"], commentsEnabled: true, trafficWeight: 9 },
  { id: "resident_safety_report", sourceId: "river_radio_tv", kind: "tv_news", publishedAtMinute: 1_080, title: "民生台探访清平河：颜色仍在扩散", body: report("记者在东平码头拍摄到河面仍有明显蓝色带，现场已设置警示线。", "多名钓友称先看到鱼浮头，随后才注意到支管方向出现蓝色水体。", "河道颜色来源和鱼群异常原因仍需分别调查。"), claims: [{ factId: "blue_video_real", relation: "supports" }, { factId: "fish_due_tracer", relation: "denies" }], misleadingTechniques: [], commentsEnabled: false, trafficWeight: 7 },
  { id: "dead_fish_old_photo", sourceId: "green_watch", kind: "post", publishedAtMinute: 1_440, title: "满河死鱼，谁还敢说没毒", body: "贴文首图没有日期，评论指出远处旧桥两年前已经拆除。", claims: [{ factId: "old_fish_photo", relation: "supports" }], misleadingTechniques: ["time_mismatch"], commentsEnabled: true, trafficWeight: 10 },
  { id: "official_preliminary", sourceId: "environment_office", kind: "official_notice", publishedAtMinute: 1_800, title: "清平河水体初步采样情况", body: "通报称采样未发现急性毒性指标异常，正在追查显色物来源。", claims: [{ factId: "official_result_true", relation: "supports" }], misleadingTechniques: ["selective_context"], commentsEnabled: true, trafficWeight: 10 },
  { id: "deleted_tracer_notice", sourceId: "evening_news", kind: "newspaper", publishedAtMinute: 2_160, title: "管网公司曾发布蓝色示踪作业通知", body: report("记者从网页缓存找到已删除通知，承包商计划凌晨使用蓝色示踪剂检查错接管线。", "通知证明计划存在，不能单独说明实际投放量或材料去向。", "环境部门表示正在比对备案、管线图与采样结果。"), claims: [{ factId: "tracer_primary", relation: "supports" }], misleadingTechniques: [], commentsEnabled: false, trafficWeight: 8 },
  { id: "contractor_response", sourceId: "pipe_contractor", kind: "official_notice", publishedAtMinute: 2_880, title: "示踪剂按计划使用且不具急性毒性", body: "承包商承认使用示踪剂，但没有说明实际剂量和入河路径。", claims: [{ factId: "tracer_primary", relation: "supports" }, { factId: "tracer_overdose", relation: "denies" }], misleadingTechniques: ["selective_context"], commentsEnabled: true, trafficWeight: 9 },
  { id: "contractor_records_report", sourceId: "metropolitan_daily", kind: "newspaper", publishedAtMinute: 3_600, title: "工程档案显示示踪作业获批，实际投放量待说明", body: report("公开采购和施工备案显示附近管网安排过示踪作业。", "备案没有记录实际投放剂量，承包商也未提供完整作业记录。", "获得许可不等于任何操作偏差都无需说明。"), claims: [{ factId: "tracer_primary", relation: "supports" }, { factId: "tracer_overdose", relation: "speculates" }], misleadingTechniques: [], commentsEnabled: false, trafficWeight: 7 },
  { id: "angler_timeline", sourceId: "angler_he", kind: "post", publishedAtMinute: 4_320, title: "五点多鱼就浮头，六点后水才变蓝", body: "钓友贴出连续记录，称暴雨后先出现鱼浮头，随后蓝色水体才扩散。", claims: [{ factId: "fish_due_tracer", relation: "denies" }, { factId: "sewer_overflow", relation: "supports" }], misleadingTechniques: [], commentsEnabled: true, trafficWeight: 7 },
  { id: "factory_violation", sourceId: "evening_news", kind: "newspaper", publishedAtMinute: 5_760, title: "印染厂当日上午一项指标轻微超标", body: report("晚报核对监测补录，印染厂一项化学需氧量指标轻微超标。", "该记录与所有排放合规的说法不一致，但不能解释亮蓝色。", "企业存在违规不等于它必然是蓝色水体来源。"), claims: [{ factId: "factory_compliant", relation: "denies" }, { factId: "factory_caused_blue", relation: "denies" }], misleadingTechniques: [], commentsEnabled: false, trafficWeight: 8 },
  { id: "official_full_notice", sourceId: "environment_office", kind: "official_notice", publishedAtMinute: 7_200, title: "关于清平河异常水体的阶段性调查", body: "通报确认示踪剂超量经错接雨水管入河，并公布低溶解氧与雨污溢流记录。", claims: [{ factId: "tracer_overdose", relation: "supports" }, { factId: "sewer_overflow", relation: "supports" }, { factId: "factory_compliant", relation: "denies" }], misleadingTechniques: [], commentsEnabled: true, trafficWeight: 10 },
  { id: "tv_evening_river", sourceId: "river_radio_tv", kind: "tv_news", publishedAtMinute: 8_640, title: "蓝色、死鱼与企业超标并非同一原因", body: report("晚间新闻区分了蓝色水体、鱼群异常和企业超标三件事。", "示踪剂造成颜色，雨污混流造成主要鱼群异常，印染厂另有轻微违规。", "多项真实信息可以同时存在，不能被压成一个原因。"), claims: [{ factId: "tracer_primary", relation: "supports" }, { factId: "sewer_overflow", relation: "supports" }], misleadingTechniques: [], commentsEnabled: false, trafficWeight: 6 }
 ],
 groups: [
  { id: "factory_accusers", name: "问责群体", description: "追问企业责任。", initialFrenzy: 70, attention: 85, exclusivity: 70, dissentSensitivity: 76, mobilization: 72, persistence: 62, narrativeFactIds: ["factory_caused_blue"] }, { id: "factory_defenders", name: "企业拥护者", description: "维护工厂声誉。", initialFrenzy: 45, attention: 65, exclusivity: 56, dissentSensitivity: 58, mobilization: 48, persistence: 55, narrativeFactIds: ["factory_compliant"] }, { id: "river_residents", name: "河边居民", description: "关注生活安全。", initialFrenzy: 52, attention: 75, exclusivity: 38, dissentSensitivity: 46, mobilization: 40, persistence: 68, narrativeFactIds: ["blue_video_real"] }, { id: "spectators", name: "围观群体", description: "传播冲突。", initialFrenzy: 60, attention: 88, exclusivity: 30, dissentSensitivity: 32, mobilization: 70, persistence: 30, narrativeFactIds: ["fish_due_tracer"] }
 ]
};
